"""initial

Revision ID: 3bb1a36f31db
Revises: 
Create Date: 2026-05-27 14:32:25.637068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bb1a36f31db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes_granted', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('channels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_channel_id')
    )
    op.create_table('videos',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('gcs_uri', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_processing_status'), 'videos', ['processing_status'], unique=False)
    op.create_table('engagement_snapshots',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('avg_view_duration_seconds', sa.Float(), nullable=True),
    sa.Column('avg_view_percentage', sa.Float(), nullable=True),
    sa.Column('retention_curve', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('traffic_sources', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('demographics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('top_geographies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('insights',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_llm_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_video_id'), 'insights', ['video_id'], unique=False)
    op.create_table('video_analyses',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('shot_changes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('text_detections', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('face_detections', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('video_segments',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=50), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('pacing_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'segment_index', name='uq_video_segment_index')
    )
    op.create_index(op.f('ix_video_segments_video_id'), 'video_segments', ['video_id'], unique=False)
    op.create_table('insight_segments',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id', 'segment_id')
    )
    op.create_table('segment_engagement',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('avg_retention', sa.Float(), nullable=True),
    sa.Column('retention_delta', sa.Float(), nullable=True),
    sa.Column('relative_performance', sa.Float(), nullable=True),
    sa.Column('engagement_label', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['video_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_engagement_segment_id'), 'segment_engagement', ['segment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_engagement_segment_id'), table_name='segment_engagement')
    op.drop_table('segment_engagement')
    op.drop_table('insight_segments')
    op.drop_index(op.f('ix_video_segments_video_id'), table_name='video_segments')
    op.drop_table('video_segments')
    op.drop_table('video_analyses')
    op.drop_index(op.f('ix_insights_video_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_table('insights')
    op.drop_table('engagement_snapshots')
    op.drop_index(op.f('ix_videos_processing_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_table('channels')
    op.drop_table('users')
    # ### end Alembic commands ###
