"""1779892930_add_top_comments

Revision ID: e3671d97d897
Revises: 3bb1a36f31db
Create Date: 2026-05-27 16:42:11.565424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3671d97d897'
down_revision: Union[str, None] = '3bb1a36f31db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_snapshots', sa.Column('top_comments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_snapshots', 'top_comments')
    # ### end Alembic commands ###
